[phases.setup]
nixPkgs = ['python312', 'gcc']

[phases.install] 
cmd = 'pip install -r requirements.txt'

[phases.start]
cmd = 'python main.py
[phases.setup]
nixPkgs = ['python312', 'gcc']

[phases.install] 
cmd = 'pip install -r requirements.txt'

[phases.start]
cmd = 'python main.py'
